sonar.projectKey=Kamzazik_qa-auto-engineer-javascript-project-87
sonar.organization=kamzazik
sonar.host.url=https://sonarcloud.io
sonar.token=${env.SONAR_TOKEN}

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/__tests__/**,**/*.test.js